### ISSUE TITLE
is there pre compiled version?

### ISSUE THREAD

**Issue by youxiaojie** [ogdenpm/disktools#1]
is there pre compiled version?

**Comment by ogdenpm** [comment]
Hi
Precompiled versions are in the prebuilt directory

regards
Mark
    	















is there pre compiled version?

**Comment by youxiaojie** [comment]
I hope to use the floppy disk image in virtualbox, the original is td0 format(dos,sco unix and os/2), which format is recognised by virtualbox? Which format is compatible with dd comand and can be mount in linux?raw format?iand does raw format recognised by virtual box?i see it ended with *.ima:( some confused. thanks!!!

**Comment by ogdenpm** [comment]
Which specific tool were you intending to use from the repository?
Most of the tools  create IMD or IMG files. 
For reading using dd I would suggest IMG is the most suitable format to create, so if you have an existing .td0 file then using td02img is probably the most appropriate tool.
Note various archive tools can also read dos disk IMG files so you may be able to extract required files this way.
You may also consider using winimage which I believe can create the appropriate files for virtualbox

**Comment by youxiaojie** [comment]
does winimage's file can be used by dd? and how about the imd files? is imd can be used by virtual box and dd comand?

**Comment by ogdenpm** [comment]
Hi
Although there are many disk image formats available, the three I have been discussing are
.IMG - this is simply all of the disk data laid out consecutively sector  after sector, track after track. dd will be able to read this a simple file and potentially write to a real/virtual disk, providing the sector & track information matches.  Although I believe virtualbox used to be able to read these, I am not sure it does now.

.IMD - this format has additional embedded information that records sector/track and head and will optionally compress sectors containing repeated data, typically unused sectors. I am not aware that virtualbox can mount these directly.

.IMA is yet another disk image format, which unfortunately I don't have the details on, but I aware that winimage can convert between .IMG and .IMA and that virtualbox can load .IMA files.

I suspect there are other tools that  will convert .IMG files into a form that virtual box can read, and a very quick web search suggested vboxmanage may be able to do a conversion. Do a search for "load .img files on virtualbox" and you should see several articles. As I don't currently run virtualbox I cannot check them out.

**Comment by youxiaojie** [comment]
thanks very much!
